version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: board_game_corner_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: board_game_corner
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge