version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: board_game_corner_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --log-bin-trust-function-creators=1 #enable triggers

networks:
  default:
    driver: bridge